# Generated by Django 5.0a1 on 2023-10-19 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
