# Generated by Django 4.2.2 on 2023-08-04 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "user_choices",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CHOICE_ANSWER", "Choice answer"),
                            ("OK", "Okay"),
                            ("NO", "No"),
                            ("I_AM_NOT_SURE", "I am not sure"),
                        ],
                        default="CHOICE_ANSWER",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAnswers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
