# Generated by Django 4.2.2 on 2023-08-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useranswers",
            name="user_choices",
        ),
        migrations.AlterField(
            model_name="content",
            name="user_choices",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHOICE ANSWER", "Choice answer"),
                    ("OK", "Okay"),
                    ("NO", "No"),
                    ("I AM NOT SURE", "I am not sure"),
                ],
                default="CHOICE_ANSWER",
                max_length=20,
                null=True,
            ),
        ),
    ]
