# Generated by Django 4.2.2 on 2023-08-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
