# Generated by Django 4.2.2 on 2023-07-13 07:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0002_content_content_content_created_at_content_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="content",
            new_name="text",
        ),
        migrations.AddField(
            model_name="content",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="content",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 7, 13, 10, 55, 29, 251715)
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 7, 13, 10, 55, 29, 251715)
            ),
        ),
    ]
