# Generated by Django 4.2.2 on 2023-07-15 13:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0003_rename_content_content_text_content_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2023, 7, 15, 16, 57, 15, 776630),
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2023, 7, 15, 16, 57, 15, 776630),
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Content",
        ),
    ]
