# Generated by Django 4.2.2 on 2023-08-05 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_remove_useranswers_user_choices_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswers",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="content.content"
            ),
        ),
    ]
