# Generated by Django 4.2.2 on 2023-08-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_alter_content_user_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="user_choices",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Yes"),
                    ("2", "No"),
                    ("3", "I Am Not Sure"),
                    ("Choice answer:", "Choice Answer"),
                ],
                default="Choice answer:",
                max_length=20,
            ),
        ),
    ]
