# Generated by Django 4.2.2 on 2023-08-06 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_alter_useranswers_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswers",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING, to="content.content"
            ),
        ),
    ]
