# Generated by Django 4.2.2 on 2023-07-16 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_alter_usercontent_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercontent",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 7, 16, 16, 57, 10, 92082)
            ),
        ),
        migrations.AlterField(
            model_name="usercontent",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 7, 16, 16, 57, 10, 92082)
            ),
        ),
    ]
