# Generated by Django 4.2.2 on 2023-07-16 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_alter_usercontent_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontent",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="usercontent",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 7, 16, 17, 44, 24, 205653)
            ),
        ),
        migrations.AlterField(
            model_name="usercontent",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 7, 16, 17, 44, 24, 206653)
            ),
        ),
    ]
