# Generated by Django 4.2.2 on 2023-08-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_useranswers_choices_alter_useranswers_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="user",
        ),
        migrations.AlterField(
            model_name="content",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
