# Generated by Django 4.2.2 on 2023-07-17 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0008_alter_usercontent_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercontent",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 7, 17, 12, 18, 14, 557876)
            ),
        ),
        migrations.AlterField(
            model_name="usercontent",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 7, 17, 12, 18, 14, 557876)
            ),
        ),
    ]
