# Generated by Django 4.2.2 on 2023-07-17 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_alter_usercontent_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercontent",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 7, 17, 12, 57, 53, 848555)
            ),
        ),
        migrations.AlterField(
            model_name="usercontent",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 7, 17, 12, 57, 53, 848555)
            ),
        ),
    ]
