# Generated by Django 4.2.2 on 2023-07-29 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0035_alter_content_created_at_alter_content_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 7, 29, 16, 40, 5, 981955)
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 7, 29, 16, 40, 5, 981955)
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="user_choices",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("I am not sure", "I Am Not Sure"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
