# Generated by Django 4.2.2 on 2023-07-30 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0043_useranswers_id_alter_useranswers_user_answers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="user",
        ),
        migrations.AddField(
            model_name="useranswers",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="useranswers",
            name="user_answers",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="content.content"
            ),
        ),
    ]
