# Generated by Django 4.2.2 on 2023-07-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0045_remove_content_user_choices_useranswers_user_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentAnswerChoiceForm",
            fields=[
                (
                    "useranswers_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.useranswers",
                    ),
                ),
            ],
            bases=("content.useranswers",),
        ),
    ]
