# Generated by Django 4.2.2 on 2023-07-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0046_contentanswerchoiceform"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useranswers",
            name="user_answers",
        ),
        migrations.AddField(
            model_name="useranswers",
            name="user_answers",
            field=models.ManyToManyField(to="content.content"),
        ),
    ]
