# Generated by Django 4.2.2 on 2023-07-30 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0047_remove_useranswers_user_answers_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContentAnswerChoiceForm",
        ),
    ]
