# Generated by Django 4.2.2 on 2023-07-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0048_delete_contentanswerchoiceform"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useranswers",
            name="user_choices",
        ),
        migrations.AddField(
            model_name="content",
            name="user_choices",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("I am not sure", "I Am Not Sure"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
