# Generated by Django 4.2.2 on 2023-07-30 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0049_remove_useranswers_user_choices_content_user_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useranswers",
            name="user_answers",
        ),
        migrations.AddField(
            model_name="useranswers",
            name="user_answers",
            field=models.OneToOneField(
                default=3,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="content.content",
            ),
            preserve_default=False,
        ),
    ]
