# Generated by Django 4.2.2 on 2023-07-31 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("content", "0050_remove_useranswers_user_answers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useranswers",
            name="user_answers",
        ),
        migrations.AddField(
            model_name="content",
            name="content_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="content",
            name="object_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
