# Generated by Django 4.2.2 on 2023-07-31 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "content",
            "0051_remove_useranswers_user_answers_content_content_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswers",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="content.content"
            ),
        ),
    ]
