# Generated by Django 4.2.2 on 2023-07-31 05:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0052_alter_useranswers_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="slug",
        ),
    ]
