# Generated by Django 4.2.2 on 2023-07-31 05:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0053_remove_content_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="content",
            name="object_id",
        ),
    ]
