# Generated by Django 4.2.2 on 2023-07-31 06:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0055_useranswers_content_id_alter_useranswers_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useranswers",
            old_name="user",
            new_name="user_id",
        ),
    ]
