# Generated by Django 4.2.2 on 2023-07-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0056_rename_user_useranswers_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="user_choices",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("I am not sure", "I Am Not Sure"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
