# Generated by Django 4.2.2 on 2023-07-31 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0057_alter_content_user_choices"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useranswers",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="useranswers",
            name="content_id",
        ),
        migrations.AddField(
            model_name="content",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useranswers",
            name="content",
            field=models.ManyToManyField(to="content.content"),
        ),
    ]
