# Generated by Django 4.2.2 on 2023-08-02 10:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WEBContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2023, 8, 2, 13, 53, 14, 589643),
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2023, 8, 2, 13, 53, 14, 590643),
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
