# Generated by Django 4.2.2 on 2023-08-08 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_alter_webcontent_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="webcontent",
            old_name="image",
            new_name="photos",
        ),
        migrations.AddField(
            model_name="webcontent",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="webcontent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="webcontent",
            name="updated_at",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
