# Generated by Django 4.2.2 on 2023-08-08 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_rename_image_webcontent_photos_webcontent_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webcontent",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="webcontent",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="webcontent",
            name="photos",
        ),
        migrations.RemoveField(
            model_name="webcontent",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="webcontent",
            name="text",
        ),
        migrations.RemoveField(
            model_name="webcontent",
            name="title",
        ),
        migrations.RemoveField(
            model_name="webcontent",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="webcontent",
            name="user",
        ),
    ]
