# Generated by Django 4.2.2 on 2023-07-31 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2023, 7, 31, 15, 0, 32, 269682),
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2023, 7, 31, 15, 0, 32, 269682),
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("photos", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
