# Generated by Django 4.2.2 on 2023-08-06 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("global_content", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalcontent",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 8, 6, 14, 45, 47, 969828)
            ),
        ),
        migrations.AlterField(
            model_name="globalcontent",
            name="photos",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="globalcontent",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 8, 6, 14, 45, 47, 969828)
            ),
        ),
    ]
