# Generated by Django 4.2.5 on 2023-09-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("global_content", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalcontent",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
