# Generated by Django 4.2.2 on 2023-07-31 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("global_content", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalcontent",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 7, 31, 16, 21, 22, 93933)
            ),
        ),
        migrations.AlterField(
            model_name="globalcontent",
            name="photos",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="globalcontent",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 7, 31, 16, 21, 22, 93933)
            ),
        ),
    ]
