# Generated by Django 4.2.5 on 2023-09-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("global_content", "0004_alter_globalcontent_photos_alter_globalcontent_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalcontent",
            name="photos",
        ),
        migrations.AddField(
            model_name="globalcontent",
            name="file",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="files"
            ),
        ),
    ]
