# Generated by Django 4.2.2 on 2023-08-06 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("global_content", "0005_alter_globalcontent_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalcontent",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 8, 6, 13, 39, 44, 807620, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="globalcontent",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 8, 6, 13, 39, 44, 807620, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
