# Generated by Django 4.2.2 on 2023-08-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("global_content", "0009_alter_globalcontent_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalcontent",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="globalcontent",
            name="photos",
            field=models.ImageField(blank=True, null=True, upload_to="photos"),
        ),
    ]
